src/retrieveOutput/objects/Account.object
<CustomObject>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PropertyTriggerHelper.cls
public class PropertyTriggerHelper {
    public static Boolean accFlag = true;
    public static void propertyStatusSync(List <Property__c> newList, Map<Id,Property__c> oldMap){
        if(accFlag){
            Map<Id,String> propertyIdStatusMap = new Map<Id,String>(); 
            for(Property__c newproperty : newList){
                if(newproperty.Status__c != oldMap.get(newproperty.Id).Status__c){
                    propertyIdStatusMap.put(newproperty.id,newproperty.Status__c);
                }
            }
            if(!propertyIdStatusMap.isEmpty()){
                AccountTriggerHelper.propertyFlag = false;
                Map<Id,Account> mapAcc = new Map<Id ,Account>([Select Status__c, Property__r.Id  from Account where Property__r.Id In :propertyIdStatusMap.keySet()]);
                if(!mapAcc.isEmpty()){
                    for(Account acc: mapAcc.values()){
                        acc.Status__c = propertyIdStatusMap.get(acc.Property__r.Id);
                    }
                    update mapAcc.values();
                }
            }
        }
    }
}